version: "3.8"

services:
  server:
    build: ./server
    expose:
      - ${SERVER_PORT}
    environment:
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: npm run dev

  client:
    build: ./client
    depends_on:
      - server
    stdin_open: true
    environment:
      CLIENT_PORT: ${CLIENT_PORT}
    expose:
      - ${CLIENT_PORT}
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - ./client/src:/app/client/src
      - ./client/public:/app/client/public
    command: npm start
