version: "3.8"

services:
  server:
    build: ./server
    expose:
      - ${SERVER_PORT}
    environment:
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./

  client:
    build: ./client
    environment: -${CLIENT_PORT}
    volumes:
      - ./src:/app/src
    ports:
      - "5000:3000"
    restart: unless-stopped
    stdin_open: true
